import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'

export default function Home() {
  const [data, setData] = useState(() => {
   const y = {"Search":[{"Title":"RED","Year":"2010","imdbID":"tt1245526","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMzg2Mjg1OTk0NF5BMl5BanBnXkFtZTcwMjQ4MTA3Mw@@._V1_SX300.jpg"},{"Title":"Red Notice","Year":"2021","imdbID":"tt7991608","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZmRjODgyMzEtMzIxYS00OWY2LTk4YjUtMGMzZjMzMTZiN2Q0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg"},{"Title":"Red Dragon","Year":"2002","imdbID":"tt0289765","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOTAwZDI1OTctN2Q5YS00OGNiLWIyMmUtYWM4ZGFjYWYyYzJjXkEyXkFqcGdeQXVyMTUzMDUzNTI3._V1_SX300.jpg"},{"Title":"The Hunt for Red October","Year":"1990","imdbID":"tt0099810","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZDdkODg3YzctMGVmZS00ZDM5LWIzNTctZDRlMjA5Mjc4MGViXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg"},{"Title":"The Thin Red Line","Year":"1998","imdbID":"tt0120863","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYjEzMTM2NjAtNWFmZC00MTVlLTgyMmQtMGQyNTFjZDk5N2NmXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg"},{"Title":"Red Sparrow","Year":"2018","imdbID":"tt2873282","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTA3MDkxOTc4NDdeQTJeQWpwZ15BbWU4MDAxNzgyNTQz._V1_SX300.jpg"},{"Title":"RED 2","Year":"2013","imdbID":"tt1821694","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjI2ODQ4ODY3Nl5BMl5BanBnXkFtZTcwNTc2NzE1OQ@@._V1_SX300.jpg"},{"Title":"Turning Red","Year":"2022","imdbID":"tt8097030","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOWYxZDMxYWUtNjNiZC00MDE1LWI2Y2QtNWZhNDAyMGY5ZjVhXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg"},{"Title":"Red Eye","Year":"2005","imdbID":"tt0421239","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNzAxNjc1ODczOF5BMl5BanBnXkFtZTcwMjE3MjEzMw@@._V1_SX300.jpg"},{"Title":"Red Riding Hood","Year":"2011","imdbID":"tt1486185","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTc4NjYyMzQ5MV5BMl5BanBnXkFtZTcwNjE5Mjc3NA@@._V1_SX300.jpg"}],"totalResults":"5643","Response":"True"};
  return y.Search;
});
  const [nameState, setNameState] = useState("red");
 
  const handlerSubmit = event => {
    event.preventDefault();
        fetch('https://www.omdbapi.com/?apikey=a2b07930&s=' + nameState)
      .then((res) => res.json())
      .then((data) => {
        setData(data.Search)
      })
    
  };

  const handlerChange = event => {
    setNameState(event.target.value);
  };

  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <p>ЛОГО</p>
        <ul>
  <li><a href="https://hd.kinopoisk.ru/">Онлайн кинотеатр</a></li>
  <li><a href="https://www.kinopoisk.ru/special/oscar/?utm_source=kinopoisk&utm_medium=selfpromo_kp&utm_campaign=button_header">Оскар 2023</a></li>
</ul>
<form onSubmit={handlerSubmit}>
      <input className="input"
        type="text"
        placeholder="Input name"
        value={nameState}
        onChange={handlerChange}
        required
      />
      <input className="button" type="submit" value="Click me" />
    </form>
        </nav>
      </header>
      <main>
          {data.map((ev) => (
      <a key={ev.imdbID} href={`https://www.imdb.com/title/${ev.imdbID}`}>
        <h2 className="h2_text">{ev.Title}</h2>
        <Image className="img_bottom" src={ev.Poster} alt={ev.Title} width={300} height={300}/>
      </a>
))}
      </main>
      <footer>
      Copyright &copy; 2017 All Rights Reserved by 
      </footer>
    </>
  )
}


